@startuml

title __DAO_INTERFACES's Class Diagram__\n

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOAPeu {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOAllotjament {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOBicicleta {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOCamping {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOCasaRural {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOComarca {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOCotxe {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOEtapa {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOGrup {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOGrupFormatPerPersones {
                {abstract} + getByCorreu_Persona()
                {abstract} + getById_Grup()
                {abstract} + getByIds_AND_OR()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOHotel {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOLocalitat {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOOpinio {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOPersona {
                {abstract} + findPersonaByCorreu()
                {abstract} + findPersonaByUserNameAndPassword()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOPersonesRealitzaRuta {
                {abstract} + getByCorreu_Persona()
                {abstract} + getById_Ruta()
                {abstract} + getByIds_AND_OR()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOPuntDePas {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAORefugi {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAORelacioComarcaRuta {
                {abstract} + getComarquesByRuta()
                {abstract} + getRutesByComarca()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAORelacioComarcaRuta_2 {
                {abstract} + getById_Comarca()
                {abstract} + getById_Ruta()
                {abstract} + getByIds_AND_OR()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOReserva {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAORuta {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTipusOpinio {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTipusVot {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTram {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTramEtapa {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTramTrack {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTransport {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTransportPossiblePerAlTram {
                {abstract} + getById_Tram()
                {abstract} + getById_Transport()
                {abstract} + getByIds_AND_OR()
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOTripUB {
            }
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          namespace DAO_Interfaces {
            interface ub.edu.resources.dao.DAO_Interfaces.DAOVot {
            }
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
