@startuml

title __DAO's Class Diagram__\n

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          interface ub.edu.resources.dao.DAO {
              {abstract} + add()
              {abstract} + delete()
              {abstract} + getAll()
              {abstract} + getById()
              {abstract} + update()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          class ub.edu.resources.dao.Parell {
              + Parell()
              + Parell()
              + getElement1()
              + getElement2()
              + setElement1()
              + setElement2()
              + toString()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          class ub.edu.resources.dao.Quartet {
              + Quartet()
              + Quartet()
              + getElement1()
              + getElement2()
              + getElement3()
              + getElement4()
              + setElement1()
              + setElement2()
              + setElement3()
              + setElement4()
              + toString()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace b.edu {
      namespace resources {
        namespace dao {
          class ub.edu.resources.dao.Triplet {
              + Triplet()
              + Triplet()
              + getElement1()
              + getElement2()
              + getElement3()
              + setElement1()
              + setElement2()
              + setElement3()
              + toString()
          }
        }
      }
    }
  }
  

  ub.edu.resources.dao.Parell o-- T : element1
  ub.edu.resources.dao.Parell o-- V : element2
  ub.edu.resources.dao.Quartet o-- T : element1
  ub.edu.resources.dao.Quartet o-- V : element2
  ub.edu.resources.dao.Quartet o-- W : element3
  ub.edu.resources.dao.Quartet o-- X : element4
  ub.edu.resources.dao.Triplet o-- T : element1
  ub.edu.resources.dao.Triplet o-- V : element2
  ub.edu.resources.dao.Triplet o-- W : element3


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
